# Generated by Django 3.1.7 on 2021-03-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titles', models.CharField(max_length=200)),
                ('Amount', models.FloatField()),
                ('Date', models.DateTimeField()),
                ('Remarks', models.TextField(blank=True)),
            ],
        ),
    ]
